package cn.wxn.killkill.model.mapper;

import cn.wxn.killkill.model.entities.ItemKill;
import cn.wxn.killkill.model.entities.ItemKillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

@Repository
public interface ItemKillMapper {

    List<ItemKill> selectAll();

    ItemKill selectById(Integer id);

    ItemKill selectByIdForUpdate(Integer id);

    Integer updateKillItem(Integer id);

    Integer updateKillItemUncheck(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    long countByExample(ItemKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int deleteByExample(ItemKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int insert(ItemKill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int insertSelective(ItemKill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    List<ItemKill> selectByExample(ItemKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    ItemKill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") ItemKill record, @Param("example") ItemKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByExample(@Param("record") ItemKill record, @Param("example") ItemKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByPrimaryKeySelective(ItemKill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByPrimaryKey(ItemKill record);
}