package cn.wxn.killkill.model.mapper;

import cn.wxn.killkill.model.entities.ItemKillSuccess;
import cn.wxn.killkill.model.entities.ItemKillSuccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

@Repository
public interface ItemKillSuccessMapper {

    Integer selectByKillUser(@Param("killId") Integer killId,@Param("userId") Integer userId);

    Integer selectByKillUserForUpdate(@Param("killId") Integer killId,@Param("userId") Integer userId);

    Integer selectByKillUserInShareMode(@Param("killId") Integer killId,@Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    long countByExample(ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int deleteByExample(ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int insert(ItemKillSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int insertSelective(ItemKillSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    List<ItemKillSuccess> selectByExample(ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    ItemKillSuccess selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") ItemKillSuccess record, @Param("example") ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByExample(@Param("record") ItemKillSuccess record, @Param("example") ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByPrimaryKeySelective(ItemKillSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    int updateByPrimaryKey(ItemKillSuccess record);
}