package cn.wxn.killkill.model.entities;

import java.util.Date;

public class ItemKillSuccess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.code
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.item_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.kill_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Integer killId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.user_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.status
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.create_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.code
     *
     * @return the value of item_kill_success.code
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.code
     *
     * @param code the value for item_kill_success.code
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.item_id
     *
     * @return the value of item_kill_success.item_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.item_id
     *
     * @param itemId the value for item_kill_success.item_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.kill_id
     *
     * @return the value of item_kill_success.kill_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Integer getKillId() {
        return killId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.kill_id
     *
     * @param killId the value for item_kill_success.kill_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setKillId(Integer killId) {
        this.killId = killId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.user_id
     *
     * @return the value of item_kill_success.user_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.user_id
     *
     * @param userId the value for item_kill_success.user_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.status
     *
     * @return the value of item_kill_success.status
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.status
     *
     * @param status the value for item_kill_success.status
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.create_time
     *
     * @return the value of item_kill_success.create_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.create_time
     *
     * @param createTime the value for item_kill_success.create_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}