package cn.wxn.killkill.model.entities;

import java.util.Date;

public class ItemKill {

    private String itemName;

    private Integer canKill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill.id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill.item_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill.total
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill.start_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill.end_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill.is_active
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill.create_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill.id
     *
     * @return the value of item_kill.id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill.id
     *
     * @param id the value for item_kill.id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill.item_id
     *
     * @return the value of item_kill.item_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill.item_id
     *
     * @param itemId the value for item_kill.item_id
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill.total
     *
     * @return the value of item_kill.total
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill.total
     *
     * @param total the value for item_kill.total
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill.start_time
     *
     * @return the value of item_kill.start_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill.start_time
     *
     * @param startTime the value for item_kill.start_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill.end_time
     *
     * @return the value of item_kill.end_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill.end_time
     *
     * @param endTime the value for item_kill.end_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill.is_active
     *
     * @return the value of item_kill.is_active
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill.is_active
     *
     * @param isActive the value for item_kill.is_active
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill.create_time
     *
     * @return the value of item_kill.create_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill.create_time
     *
     * @param createTime the value for item_kill.create_time
     *
     * @mbg.generated Mon Aug 17 20:31:24 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public Integer getCanKill() {
        return canKill;
    }

    public void setCanKill(Integer canKill) {
        this.canKill = canKill;
    }

    @Override
    public String toString() {
        return "ItemKill{" +
                "itemName='" + itemName + '\'' +
                ", canKill=" + canKill +
                ", id=" + id +
                ", itemId=" + itemId +
                ", total=" + total +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                ", isActive=" + isActive +
                ", createTime=" + createTime +
                '}';
    }
}